package java;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ViduraDan
 */

import java.util.*;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import com.alee.laf.WebLookAndFeel;

import de.nixosoft.jlr.JLRGenerator;
import de.nixosoft.jlr.JLROpener;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ImageIcon;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
	 public String paper;
		
		public static HashMap < Integer, Object> mapper=new HashMap();
		public int mcc=0;
		public int mcm=0;
		
		private String end="\\end{expaper}\r\n" +
				"\\end{document}\r\n ";
		private  String  endmark="\\begin{center}\r\n"+
	             "----- ***** -----\r\n"+
	              "\\end{center}\r\n";
		
		private String stmcq="\\begin{subqlist}\r\n";
		private String enmcq="\\end{subqlist}\r\n"+
	                           "}\r\n";

		protected MainFrame a;
		public static String mcq="";
		public static String std="";
	
	
    public void date(){
        Calendar cal=new GregorianCalendar();
        int day =cal.get(Calendar.DAY_OF_MONTH);
        int month =cal.get(Calendar.MONTH)+1;
        int year =cal.get(Calendar.YEAR);
        String day2=Integer.toString(day);
        String month2=Integer.toString(month);
        String year2=Integer.toString(year);
        
        date.setText("Date :"+day2+"/"+month2+"/"+year2);
    }
    
    public void time(){
        Thread time=new Thread(){
            public void run()
            {
                try {  
                    for(;;){
        Calendar cal2=new GregorianCalendar();
        int second =cal2.get(Calendar.SECOND);
        int minute =cal2.get(Calendar.MINUTE);
        int hour =cal2.get(Calendar.HOUR);
        String second2=Integer.toString(second);
        String minute2=Integer.toString(minute);
        String hour2=Integer.toString(hour);
        
        timeLabel.setText("Time :"+hour2+":"+minute2+":"+second2);
                    sleep(1000);}
                } catch (InterruptedException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
      time.start();
    }

    public home() {
        initComponents();
        date();
        time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tex = new javax.swing.JTextArea();
        newPaper = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        open = new javax.swing.JButton();
        save = new javax.swing.JButton();
        save.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		JFileChooser fs=new JFileChooser("C:\\");
        	    fs.setDialogTitle("Save a File");
        	    fs.setFileFilter(new FileTypeFilter(".txt","Text File"));
        	    fs.setFileFilter(new FileTypeFilter(".tex","latex File"));
        	    int result=fs.showSaveDialog(null);
        	    if(result == JFileChooser.APPROVE_OPTION){
        	    	String content = tex.getText();
        	    	File fi =fs.getSelectedFile();
        	    	try{
        	    		FileWriter fw=new FileWriter(fi.getPath());
        	    		
        	    		
        	    		fw.write(content);
        	    		fw.flush();
        	    		fw.close();
        	    		
        	    	}catch(Exception e2){
        	    		
        	    		JOptionPane.showMessageDialog(null,e2.getMessage());
        	    	}
        	    	
        	    	
        	    	
        	    }
        	    
        	}
        });
        totalQuestions = new javax.swing.JTextField();
        totalMarks = new javax.swing.JTextField();
        mcqNo = new javax.swing.JTextField();
        mcqMarks = new javax.swing.JTextField();
        structuredNo = new javax.swing.JTextField();
        structuredMarks = new javax.swing.JTextField();
        essayMarks = new javax.swing.JTextField();
        essayNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pdf1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        mcqAdd = new javax.swing.JButton();
        EssayAdd = new javax.swing.JButton();
        structuredAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        searchQuestions = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        addQuestions1 = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        moduleLabel = new javax.swing.JLabel();
        btLabel = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox<>();
        moduleComboBox = new javax.swing.JComboBox<>();
        btComboBox = new javax.swing.JComboBox<>();
        queSearchButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        searchQuestions1 = new javax.swing.JLabel();
        domainLabel = new javax.swing.JLabel();
        bthComboBox = new javax.swing.JComboBox<>();
        btSearchButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem11.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new BT().setVisible(true);
        	}
        });
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu4.setText("jMenu4");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QseTeX");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tex.setColumns(20);
        tex.setRows(5);
        jScrollPane1.setViewportView(tex);

        newPaper.setIcon(new ImageIcon("C:\\Users\\User\\workspace\\GPFF\\images\\NewDocument_32x32.png")); // NOI18N
        newPaper.setToolTipText("New Paper");
        newPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaperActionPerformed(evt);
            }
        });

        refresh.setIcon(new ImageIcon("C:\\Users\\User\\workspace\\GPFF\\images\\112_RefreshArrow_Blue_32x32.png")); // NOI18N
        refresh.setToolTipText("Refresh");

        open.setIcon(new ImageIcon("C:\\Users\\User\\workspace\\GPFF\\images\\base_floppydisk_32.png")); // NOI18N
        open.setToolTipText("Open");

        save.setIcon(new ImageIcon("C:\\Users\\User\\workspace\\GPFF\\images\\pdf.png")); // NOI18N
        save.setToolTipText("Save");

        totalQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalQuestionsActionPerformed(evt);
            }
        });

        totalMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMarksActionPerformed(evt);
            }
        });

        mcqNo.setText(" ");

        mcqMarks.setText(" ");

        structuredNo.setText(" ");

        structuredMarks.setText(" ");

        essayMarks.setText(" ");

        essayNo.setText(" ");

        jLabel1.setText("Total Questions");

        jLabel2.setText("Total Marks");

        jLabel3.setText("MCQ");

        jLabel4.setText("MCQ");

        jLabel5.setText("Structured");

        jLabel6.setText("Structured");

        jLabel7.setText("Essay");

        jLabel8.setText("Essay");

        pdf1.setIcon(new ImageIcon("C:\\Users\\User\\workspace\\GPFF\\images\\on-button.png")); // NOI18N
        pdf1.setToolTipText("PDF View");
        pdf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf1ActionPerformed(evt);
            }
        });

        mcqAdd.setText(" ");
        mcqAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcqAddActionPerformed(evt);
            }
        });

        EssayAdd.setText(" ");
        EssayAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EssayAddActionPerformed(evt);
            }
        });

        structuredAdd.setText(" ");
        structuredAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                structuredAddActionPerformed(evt);
            }
        });

        jLabel9.setText("MCQ");

        jLabel10.setText("Structured");

        jLabel11.setText("Essay");

        searchQuestions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchQuestions.setForeground(new java.awt.Color(102, 102, 102));
        searchQuestions.setText("Search Questions");

        addQuestions1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addQuestions1.setForeground(new java.awt.Color(102, 102, 102));
        addQuestions1.setText("Add Questions");

        subjectLabel.setText("Subject");

        moduleLabel.setText("Module");

        btLabel.setText("Bloom's Tax Domain");

        queSearchButton.setText("Search");

        searchQuestions1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchQuestions1.setForeground(new java.awt.Color(102, 102, 102));
        searchQuestions1.setText("Bloom's Taxanomy Help");

        domainLabel.setText("Domain");

        btSearchButton.setText("Search");
        btSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchButtonActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeLabel.setText("Time");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("|");

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setText("Date");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New Paper");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Log Out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Insert");

        jMenuItem5.setText("MCQ");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Structured");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Essay");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("PDF View");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Tools");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Bloom's Taxanomy Help");
        jMenu6.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Search Question");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Help");

        jMenuItem13.setText("User Manual");
        jMenu7.add(jMenuItem13);
        jMenu7.add(jSeparator4);

        jMenuItem14.setText("About");
        jMenu7.add(jMenuItem14);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mcqAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel9)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(structuredAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel11))
                                        .addComponent(EssayAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                            .addComponent(jSeparator2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(moduleLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(moduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(subjectLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(queSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jSeparator3)
                                    .addContainerGap())
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(domainLabel)
                                    .addGap(60, 60, 60)
                                    .addComponent(bthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(searchQuestions1)
                                    .addContainerGap()))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchQuestions)
                                    .addComponent(addQuestions1))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pdf1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(timeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(totalQuestions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mcqMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mcqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(structuredMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(structuredNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(essayMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(essayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(newPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(open, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(essayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(essayMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(structuredNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(structuredMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(totalQuestions)
                                            .addComponent(mcqNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(totalMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mcqMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pdf1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLabel)
                            .addComponent(jLabel13)
                            .addComponent(date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(addQuestions1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mcqAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EssayAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(structuredAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectLabel)
                            .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moduleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(queSearchButton)
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchQuestions1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domainLabel)
                            .addComponent(bthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btSearchButton)
                        .addGap(0, 58, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //new NewPaper().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        //new Essay().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void newPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaperActionPerformed
        // TODO add your handling code here:
    	MainFrame.mcq="";
    	
    	tex.setText("");
    	mcc=0;
    	mcm=0;
    	//mapper=new HashMap();
    	mapper.clear();
        //new NewPaper().setVisible(true);
    }//GEN-LAST:event_newPaperActionPerformed
    
public void mcqupd(){
    	
    	String upd=paper+mcq+endmark+end;
    	try{
			  PrintWriter writer = new PrintWriter("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates\\latex.tex", "UTF-8");
			  writer.println(upd);
			  writer.close();
			  
			 /* gp a=new gp();
			  a.frmPrototype.setVisible(true);*/
			 // g.setVisible(true);
			  DefaultListModel listModel = new DefaultListModel();
			  tex.setText("");
			  try{
			  BufferedReader in=new BufferedReader(new FileReader("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates\\latex.tex"));
			  String line=null;
			  while((line=in.readLine())!=null){
				  listModel.addElement(line);
				  tex.append(line+"\n");
			  }
			  //a.tex.setModel(listModel);
			  //tex.setModel(listModel);
			  }
			  catch(Exception e){
				  e.printStackTrace();
				  
			  }
			  
			  
			  
			  
		  }catch(Exception e){
			  e.printStackTrace();
			 
			  
		  } 
    	
    	
    	
    	
    }

public void stdupd(){
	
	String upd2=paper+std+endmark+end;
	try{
		  PrintWriter writer2 = new PrintWriter("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates\\latex.tex", "UTF-8");
		  writer2.println(upd2);
		  writer2.close();
		  
		 /* gp a=new gp();
		  a.frmPrototype.setVisible(true);*/
		 // g.setVisible(true);
		  DefaultListModel listModel = new DefaultListModel();
		  tex.setText("");
		  try{
		  BufferedReader in2=new BufferedReader(new FileReader("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates\\latex.tex"));
		  String line2=null;
		  while((line2=in2.readLine())!=null){
			  listModel.addElement(line2);
			  tex.append(line2+"\n");
		  }
		  //a.tex.setModel(listModel);
		  //tex.setModel(listModel);
		  }
		  catch(Exception e){
			  e.printStackTrace();
			  
		  }
		  
		  
		  
		  
	  }catch(Exception e){
		  e.printStackTrace();
		 
		  
	  } 
	
	
	
	
}

    private void totalMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMarksActionPerformed

    private void totalQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalQuestionsActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void pdf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf1ActionPerformed
        // TODO add your handling code here:
    	try{//create pdf
			File desktop = new File(System.getProperty("user.home")	+ "\\" + "Desktop");
			File wd = new File("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates");
			File invoice1 = new File("C:\\Users\\ViduraDan\\Desktop\\fwdtemplates"+"\\"+ "latex.tex");
			JLRGenerator pdfGen = new JLRGenerator();

			pdfGen.generate(invoice1, desktop, wd);
			File pdf1 = pdfGen.getPDF();

		

			JLROpener.open(pdf1);}catch(IOException ex){ex.printStackTrace();}
    }//GEN-LAST:event_pdf1ActionPerformed

    private void btSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchButtonActionPerformed
        // TODO add your handling code here:
        //new BT().setVisible(true);
    }//GEN-LAST:event_btSearchButtonActionPerformed

    private void structuredAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_structuredAddActionPerformed
        // TODO add your handling code here:
       // new StructureQ().setVisible(true);
    }//GEN-LAST:event_structuredAddActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        //new StructureQ().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void EssayAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EssayAddActionPerformed
        // TODO add your handling code here:
        //new Essay().setVisible(true);
    }//GEN-LAST:event_EssayAddActionPerformed

    private void mcqAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcqAddActionPerformed
        // TODO add your handling code here:
        //new MCQ().setVisible(true);
    }//GEN-LAST:event_mcqAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    UIManager.setLookAndFeel(new WebLookAndFeel());
} catch (Exception e) {
    e.printStackTrace();
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EssayAdd;
    private javax.swing.JLabel addQuestions1;
    private javax.swing.JComboBox<String> btComboBox;
    private javax.swing.JLabel btLabel;
    private javax.swing.JButton btSearchButton;
    private javax.swing.JComboBox<String> bthComboBox;
    private javax.swing.JLabel date;
    private javax.swing.JLabel domainLabel;
    private javax.swing.JTextField essayMarks;
    private javax.swing.JTextField essayNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea tex;
    private javax.swing.JButton mcqAdd;
    private javax.swing.JTextField mcqMarks;
    private javax.swing.JTextField mcqNo;
    private javax.swing.JComboBox<String> moduleComboBox;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JButton newPaper;
    private javax.swing.JButton open;
    private javax.swing.JButton pdf1;
    private javax.swing.JButton queSearchButton;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JLabel searchQuestions;
    private javax.swing.JLabel searchQuestions1;
    private javax.swing.JButton structuredAdd;
    private javax.swing.JTextField structuredMarks;
    private javax.swing.JTextField structuredNo;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField totalMarks;
    private javax.swing.JTextField totalQuestions;
    // End of variables declaration//GEN-END:variables
}
