/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JTextArea;

import java.awt.Component;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;

import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mufarrij
 */
public class Essay1 extends javax.swing.JFrame {

    /**
     * Creates new form StructureQ
     */
	
	public  String  tst="";
	public  String  tp ="Above";
	main1_frame g;
	
	public static JTextArea textAreaStruct = null;
	public static int curPosStruct;
	
	public String imgpath="";
	public String abimgpath="";
    
	public  Essay1(main1_frame a){
    	setResizable(false);
    	setTitle("Essay Setter");
        initComponents();
        g=a;
    }
  
	
	
    
    /*public void fillCombox()
	{
		try{
			Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/pro_db?useSSL=true","root","mysql");
			Statement st=connection.createStatement();
			String query="SELECT DISTINCT(Area) FROM bloom";
			ResultSet rs=st.executeQuery(query);
			
			while(rs.next()){
			 domain.addItem(rs.getString("Area"));
			}
			}
		catch(Exception e){
			e.printStackTrace();
		}
	}*/
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qno = new javax.swing.JSpinner();
        qno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		Integer no= (Integer) qno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    
        	    if(g.esmapper.containsKey(r)){
        	    	essayclass o=(essayclass)g.esmapper.get(r);
        	    	String tit=o.utitle;
        	    	stro st1=(stro)o.essaylist.get(1);
        	    	title.setText(tit);
        	        question.setText(st1.question);
        	        Double marks=Double.parseDouble(st1.mark);
        	        mark.setValue(marks);
        	       
        	       
        	  }else{
        		title.setText("");
      			question.setText("");
       	         }
        	}
        });
        qno.setModel(new SpinnerNumberModel(1, 1, 10, 1));
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        changeTitle = new javax.swing.JButton();
        changeTitle.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		 int no=(int) qno.getValue();
      	   	   if(g.esmapper.containsKey(no)){
      	  	    	strclass o=(strclass)g.esmapper.get(no);
      	  	    	o.title="\\question {"+title.getText()+".\r\n";
      	  	    	o.utitle=title.getText();
      	  	   }else{
      	  		   title.setText("");
      	  	   }
        	}
        });
        jLabel3 = new javax.swing.JLabel();
        subqno = new javax.swing.JSpinner();
        subqno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		Integer no= (Integer) subqno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    Integer no1=(Integer)qno.getValue();
        		essayclass mcb=(essayclass)g.esmapper.get(no1);
        		if(mcb.essaylist.containsKey(no)){
            		stro o=(stro)mcb.essaylist.get(no);
            		question.setText(o.uquestion);
        	    	Double marks=Double.parseDouble(o.mark);
        	    	mark.setValue(marks);
        	    	area.setSelectedItem(o.btarea);
            	  }
            		else{
            			question.setText("");
             	      }
        	}
        });
        subqno.setModel(new SpinnerNumberModel(1, 1, 10, 1));
        jLabel4 = new javax.swing.JLabel();
        mark = new javax.swing.JSpinner();
        mark.setModel(new SpinnerNumberModel(1.0, 1.0, 20.0, 1.0));
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        area.setModel(new DefaultComboBoxModel(new String[] {"Remembering", "Understanding", "Applying", "Analizing", "Evaluating", "Creating"}));
        addMath = new javax.swing.JButton();
        addImage = new javax.swing.JButton();
        addImage.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		JFileChooser fileChooser=new JFileChooser("C:\\");
        		FileNameExtensionFilter filter;
        		filter = new FileNameExtensionFilter("jpeg, gif and png files", "jpg", "gif", "png");
        		fileChooser.addChoosableFileFilter(filter);
        		int returnVal = fileChooser.showOpenDialog((Component)e.getSource());
        	    if (returnVal == JFileChooser.APPROVE_OPTION) {
        	        File file = fileChooser.getSelectedFile();
        	        String filename=fileChooser.getSelectedFile().getName();
        	        abimgpath=filename;
        	        try {
        	           imgpath = file.toString();
        	           
        	           String dest="C:\\Users\\User\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\+"+filename;
        	           File f1=new File(imgpath);
        	           File f2=new File(dest);
        	           Files.copy(f1.toPath(),f2.toPath(),StandardCopyOption.REPLACE_EXISTING);
        	           System.out.println(imgpath);
        	        } catch (Exception ex) {
        	          System.out.println("problem accessing file"+file.getAbsolutePath());
        	        }
        	    } 
        	    else {
        	        System.out.println("File access cancelled by user.");
        	    }
        	}
        });
        addTable = new javax.swing.JButton();
        addQuestion = new javax.swing.JButton();
        addQuestion.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		int no= (int) qno.getValue();
              	 
        		 Double mar=(Double)mark.getValue();
        		 int sqn=(int)subqno.getValue();
          	
          	
          	    String dtable="";
         		String utable="";
                 
         		if(tst!=""){
         		   if(tp=="Above"){
         			   utable =tst;
         			   
         		   }
         		   else{
         			   dtable=tst; 
         		   }
         		}
          	
         		
         		String pic="";
         		if(abimgpath!=null){
         			pic="\\includegraphics[width=0.5\\textwidth]{"+"+"+abimgpath+"}\\break\r\n";
         		      
         		}
         		
         		
         		
         		String stitle="\\newpage\r\n"+"\\question{"+title.getText()+"\r\n";
         		
          	String str=
          		  utable+"\\subquestion{"+ pic+question.getText() +"\r\n" + dtable+ 
                    
                    "\\qmarks{"+mark.getValue()+"}\r\n"+

                    "}\r\n";
                    
                   
          	String start="\\begin{subqlist}\r\n";
          	String end="\\end{subqlist}\r\n";
          	
          	
          	
          	if(g.esmapper.containsKey(no)){
          		essayclass testa=(essayclass)g.esmapper.get(no);
          		g.esmapper.remove(no);
          	    testa.title="\\newpage\r\n"+"\\question {"+title.getText()+".\r\n";
         			testa.utitle=title.getText();
          		if(testa.essaylist.containsKey(sqn)){
          			System.out.print(testa.mark);
          			stro r=(stro)testa.essaylist.get(sqn);
          			testa.essaylist.remove(sqn);
          			String oldmark=r.mark;
          			r.qno= sqn;
          	        r.question=str;
          	        r.uquestion=question.getText();
              		r.mark=mark.getValue().toString();
              		r.btarea=area.getSelectedItem().toString();
              		/*if(!testa.CheckMark()){
              			JOptionPane.showMessageDialog(null, "Marks for total questions exeeded the Limit");
              			
              		}else{
              		testa.strlist.put(sqn,r);
              		}*/
              		testa.essaylist.put(sqn,r);
              		pic="";
              		abimgpath="";
             	       }
          		else{
          			esso t=new esso(no,str);
          			t.uquestion=question.getText();
              		t.qno= sqn;
              		t.mark=mark.getValue().toString();
              		t.btarea=area.getSelectedItem().toString();
              		testa.essaylist.put(sqn,t);
          			}
          		   g.esmapper.put(no,testa);
          		   pic="";
          		   abimgpath="";
          		
          	}else{
          	
          		essayclass r=new essayclass(no);
          		r.title=stitle;
          		r.utitle=title.getText();
          		stro t=new stro(no,str);
          		t.uquestion=question.getText();
          		t.qno= sqn;
          		t.mark=mark.getValue().toString();
          		t.btarea=area.getSelectedItem().toString();
          		r.essaylist.put(sqn,t);
          		g.esmapper.put(no,r);
          		pic="";
          		abimgpath="";
          	}
          	
          	g.esset();
      		g.esupd();
      		tst="";
       		
       	}
        	
        });
        
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        domain = new javax.swing.JComboBox<>();
        
        /*keywords.setLayoutOrientation(JList.HORIZONTAL_WRAP);
		DefaultListModel model= new DefaultListModel();
        domain.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		/*try{
					Connection myConn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pro_db?useSSL=true","root","mysql");
					model.removeAllElements();
				    keywords.setModel(model);
					String query="SELECT DISTINCT Keyword FROM bloom WHERE Area=?";
					PreparedStatement pst=myConn.prepareStatement(query);
					pst.setString(1, (String)domain.getSelectedItem());
					ResultSet rs=pst.executeQuery();
					while(rs.next()){
						
						model.addElement(rs.getString("Keyword"));
						keywords.setModel(model);
					}
					}
				catch(Exception e){
					e.printStackTrace();
				}
        	}
        	
        });*/
        domain.addMouseMotionListener(new MouseMotionAdapter() {
        	@Override
        	public void mouseDragged(MouseEvent arg0) {
        		//fillCombox();
        	}
        	@Override
        	public void mouseMoved(MouseEvent arg0) {
        		//fillCombox();
        	}
        });
        jScrollPane2 = new javax.swing.JScrollPane();
        keywords = new javax.swing.JList<>();
        keywords.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		/*try{
					Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/pro_db?useSSL=true","root","mysql");
					String query="SELECT DISTINCT * FROM bloom WHERE Keyword=?";
					PreparedStatement pst=connection.prepareStatement(query);
					pst.setString(1, (String)keywords.getSelectedValue());
					ResultSet rs=pst.executeQuery();
					while(rs.next()){
					 exp.setText(rs.getString("Example"));
					}
					}
				catch(Exception e1){
					e1.printStackTrace();
				}*/
        	}
        });
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        exp = new javax.swing.JEditorPane();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Question Number");

        jLabel2.setText("Title");

        title.setText(" ");

        changeTitle.setText("Change Title");

        jLabel3.setText("Sub Question Number");

        jLabel4.setText("Marks");

        jLabel5.setText("Question");

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        jLabel8.setText("Area");

        addMath.setText("Add Math");

        addImage.setText("Add Image");

        addTable.setText("Add Table");

        addQuestion.setText("Add Question");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeTitle))
                            .addComponent(qno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subqno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addMath)
                                        .addGap(43, 43, 43)
                                        .addComponent(addImage)
                                        .addGap(51, 51, 51)
                                        .addComponent(addTable)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addQuestion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(qno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subqno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addImage)
                            .addComponent(addTable)
                            .addComponent(addMath))
                        .addGap(17, 17, 17)
                        .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(addQuestion)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Question Adding", jPanel1);

        jLabel9.setText("Domain");

        keywords.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        keywords.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane2.setViewportView(keywords);

        jLabel10.setText("Keywords");

        jLabel11.setText("Examples");

        jScrollPane3.setViewportView(exp);

        closeButton.setText("Back to Question");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bloom's Taxonomy Help", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Essay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Essay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Essay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Essay1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Essay1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImage;
    private javax.swing.JButton addMath;
    private javax.swing.JButton addQuestion;
    private javax.swing.JButton addTable;
    private javax.swing.JComboBox<String> area;
    private javax.swing.JButton changeTitle;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> domain;
    private javax.swing.JEditorPane exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> keywords;
    private javax.swing.JSpinner mark;
    private javax.swing.JSpinner qno;
    private javax.swing.JTextArea question;
    private javax.swing.JSpinner subqno;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}

