package gp;

import gp.math.jahuwaldt.jatex.MainWindow;

import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;



/**
 *
 * @author User
 */
public class essetter extends javax.swing.JFrame {
	

    /**
     * Creates new form strsetter
     */
	public  String  tst="";
	public  String  tp ="Above";
	main1_frame g;
	
	public static JTextArea textAreaStruct = null;
	public static int curPosStruct;
	
	public String imgpath="";
	public String abimgpath="";
    public  essetter(main1_frame a){
    	setResizable(false);
    	setTitle("Structure Setter");
        initComponents();
        g=a;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        addmath = new javax.swing.JToggleButton();
        addmath.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                 try {
                	
                	if(mcqseter.main != null){
                		mcqseter.main.textArea = null;
                		mcqseter.main.textField = null;
                		mcqseter.main.textPaneEssay = null;
                		mcqseter.main.curPos = curPosStruct;
                		mcqseter.main.textAreaStruct = textAreaStruct;
                		mcqseter.main.setVisible(true);
                	}else{
                		mcqseter.main = new MainWindow(null,null,null,textAreaStruct,curPosStruct);
                		mcqseter.main.setVisible(true);
                	}
                	//BufferedReader b=new BufferedReader(FileReader("math.txt"));
                	
                                          

                } catch (Throwable ex) {
                    ex.printStackTrace();
                    
                }
        	}
        });
        pic = new javax.swing.JButton();
        pic.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		JFileChooser fileChooser=new JFileChooser("C:\\");
        		FileNameExtensionFilter filter;
        		filter = new FileNameExtensionFilter("jpeg, gif and png files", "jpg", "gif", "png");
        		fileChooser.addChoosableFileFilter(filter);
        		int returnVal = fileChooser.showOpenDialog((Component)e.getSource());
        	    if (returnVal == JFileChooser.APPROVE_OPTION) {
        	        File file = fileChooser.getSelectedFile();
        	        String filename=fileChooser.getSelectedFile().getName();
        	        abimgpath=filename;
        	        try {
        	           imgpath = file.toString();
        	           
        	           String dest="C:\\Users\\User\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\+"+filename;
        	           File f1=new File(imgpath);
        	           File f2=new File(dest);
        	           Files.copy(f1.toPath(),f2.toPath(),StandardCopyOption.REPLACE_EXISTING);
        	           System.out.println(imgpath);
        	        } catch (Exception ex) {
        	          System.out.println("problem accessing file"+file.getAbsolutePath());
        	        }
        	    } 
        	    else {
        	        System.out.println("File access cancelled by user.");
        	    }
        	}
        });
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        qno = new javax.swing.JSpinner();
        qno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		
            		Integer no= (Integer) qno.getValue();
            	    String a=no.toString();
            	    int r=no.intValue();
            	    
            	    if(g.esmapper.containsKey(r)){
            	    	essayclass o=(essayclass)g.esmapper.get(r);
            	    	String tit=o.utitle;
            	    	stro st1=(stro)o.essaylist.get(1);
            	    	Title.setText(tit);
            	        question.setText(st1.question);
            	        Double marks=Double.parseDouble(st1.mark);
            	        Mark.setValue(marks);
            	       
            	       
            	  }else{
            		Title.setText("");
          			question.setText("");
           	         }
        	}
        });
        qno.setModel(new SpinnerNumberModel(1, 1, 20, 1));
        ctitle = new javax.swing.JButton();
        ctitle.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		   int no=(int) qno.getValue();
        	   	   if(g.esmapper.containsKey(no)){
        	  	    	strclass o=(strclass)g.esmapper.get(no);
        	  	    	o.title="\\question {"+Title.getText()+".\r\n";
        	  	    	o.utitle=Title.getText();
        	  	   }else{
        	  		   Title.setText("");
        	  	   }
        	}
        });
        subqno = new javax.swing.JSpinner();
        subqno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent e) {
        		Integer no= (Integer) subqno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    Integer no1=(Integer)qno.getValue();
        		essayclass mcb=(essayclass)g.esmapper.get(no1);
        		if(mcb.essaylist.containsKey(no)){
            		stro o=(stro)mcb.essaylist.get(no);
            		question.setText(o.uquestion);
        	    	Double marks=Double.parseDouble(o.mark);
        	    	Mark.setValue(marks);
        	    	Area.setSelectedItem(o.btarea);
            	  }
            		else{
            			question.setText("");
             	      }
        	}
        });
        subqno.setModel(new SpinnerNumberModel(1, 1, 8, 1));
        Mark = new javax.swing.JSpinner();
        Mark.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 1.0));
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		table5 a= new table5(this);
                a.setVisible(true);
        	}
        });
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new BT().setVisible(true);
        	}
        });
        jLabel8 = new javax.swing.JLabel();
        Area = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        add.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int no= (int) qno.getValue();
           	 
         		 Double mark=(Double)Mark.getValue();
         		 int sqn=(int)subqno.getValue();
           	
           	
           	    String dtable="";
          		String utable="";
                  
          		if(tst!=""){
          		   if(tp=="Above"){
          			   utable =tst;
          			   
          		   }
          		   else{
          			   dtable=tst; 
          		   }
          		}
           	
          		
          		String pic="";
          		if(abimgpath!=null){
          			pic="\\includegraphics[width=0.5\\textwidth]{"+"+"+abimgpath+"}\\break\r\n";
          		      
          		}
          		
          		
          		
          		String stitle="\\newpage\r\n"+"\\question{"+Title.getText()+"\r\n";
          		
           	String str=
           		  utable+"\\subquestion{"+ pic+question.getText() +"\r\n" + dtable+ 
                     
                     "\\qmarks{"+Mark.getValue()+"}\r\n"+

                     "}\r\n";
                     
                    
           	String start="\\begin{subqlist}\r\n";
           	String end="\\end{subqlist}\r\n";
           	
           	
           	
           	if(g.esmapper.containsKey(no)){
           		essayclass testa=(essayclass)g.esmapper.get(no);
           		g.esmapper.remove(no);
           	    testa.title="\\newpage\r\n"+"\\question {"+Title.getText()+".\r\n";
          			testa.utitle=Title.getText();
           		if(testa.essaylist.containsKey(sqn)){
           			System.out.print(testa.mark);
           			stro r=(stro)testa.essaylist.get(sqn);
           			testa.essaylist.remove(sqn);
           			String oldmark=r.mark;
           			r.qno= sqn;
           	        r.question=str;
           	        r.uquestion=question.getText();
               		r.mark=Mark.getValue().toString();
               		r.btarea=Area.getSelectedItem().toString();
               		/*if(!testa.CheckMark()){
               			JOptionPane.showMessageDialog(null, "Marks for total questions exeeded the Limit");
               			
               		}else{
               		testa.strlist.put(sqn,r);
               		}*/
               		testa.essaylist.put(sqn,r);
               		pic="";
               		abimgpath="";
              	       }
           		else{
           			esso t=new esso(no,str);
           			t.uquestion=question.getText();
               		t.qno= sqn;
               		t.mark=Mark.getValue().toString();
               		t.btarea=Area.getSelectedItem().toString();
               		testa.essaylist.put(sqn,t);
           			}
           		   g.esmapper.put(no,testa);
           		   pic="";
           		   abimgpath="";
           		
           	}else{
           	
           		essayclass r=new essayclass(no);
           		r.title=stitle;
           		r.utitle=Title.getText();
           		stro t=new stro(no,str);
           		t.uquestion=question.getText();
           		t.qno= sqn;
           		t.mark=Mark.getValue().toString();
           		t.btarea=Area.getSelectedItem().toString();
           		r.essaylist.put(sqn,t);
           		g.esmapper.put(no,r);
           		pic="";
           		abimgpath="";
           	}
           	
           	g.esset();
       		g.esupd();
       		tst="";
        		
        	}
        });

        jTextField2.setText("jTextField2");

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title");

        Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Question");

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        addmath.setText("AddMath");

        pic.setText("Picture");

        jLabel5.setText("Question No");

        jLabel6.setText("Subpart No");

        jLabel7.setText("Marks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 452, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        						.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(addmath)
        							.addGap(27)
        							.addComponent(pic, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel2)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(Title, GroupLayout.PREFERRED_SIZE, 418, GroupLayout.PREFERRED_SIZE))))
        					.addGap(18)
        					.addComponent(jLabel5)))
        			.addGap(116)
        			.addComponent(jLabel4)
        			.addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(2)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Title, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel4)
        						.addComponent(jLabel5))))
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jLabel6)
        					.addGap(38)
        					.addComponent(jLabel7)))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(pic)
        				.addComponent(addmath))
        			.addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        ctitle.setText("Change Title");

        jButton3.setText("Add Table");

        jButton4.setText("Bloom Texanomy");

        jLabel8.setText("Area");

        Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remembering", "Understanding", "Applying", "Analyzing", "Evaluating", "Creating", " " }));

        add.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qno)
                    .addComponent(subqno)
                    .addComponent(Mark)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ctitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subqno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(strsetter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(strsetter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(strsetter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(strsetter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new strsetter2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton pic;
    private javax.swing.JButton ctitle;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner qno;
    private javax.swing.JSpinner subqno;
    private javax.swing.JSpinner Mark;
    private javax.swing.JTextArea question;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton addmath;
    // End of variables declaration                   
}


