/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp;

import java.awt.SystemColor;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


/**
 *
 * @author ViduraDan
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main_frame
     */
    public main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        newPaper = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newPaper1 = new javax.swing.JButton();
        newPaper2 = new javax.swing.JButton();
        newPaper3 = new javax.swing.JButton();
        newPaper4 = new javax.swing.JButton();
        newPaper5 = new javax.swing.JButton();
        newPaper6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QseTeX");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        newPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/Folder_32x32.png"))); // NOI18N
        newPaper.setActionCommand("New Paper");
        newPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaperActionPerformed(evt);
            }
        });

        jLabel1.setText("New Paper");

        newPaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/newpaper.png"))); // NOI18N
        newPaper1.setActionCommand("New Paper");
        newPaper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper1ActionPerformed(evt);
            }
        });

        newPaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/diskette.png"))); // NOI18N
        newPaper2.setActionCommand("New Paper");
        newPaper2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper2ActionPerformed(evt);
            }
        });

        newPaper3.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/square.png"))); // NOI18N
        newPaper3.setActionCommand("New Paper");
        newPaper3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper3ActionPerformed(evt);
            }
        });

        newPaper4.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/email.png"))); // NOI18N
        newPaper4.setActionCommand("New Paper");
        newPaper4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper4ActionPerformed(evt);
            }
        });

        newPaper5.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/pdf.png"))); // NOI18N
        newPaper5.setActionCommand("New Paper");
        newPaper5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper5ActionPerformed(evt);
            }
        });

        newPaper6.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/inbox (1).png"))); // NOI18N
        newPaper6.setActionCommand("New Paper");
        newPaper6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Open");

        jLabel3.setText("Save");

        jLabel24.setText("PDF View");

        jLabel25.setText("Send");

        jLabel26.setText("Inbox");

        jLabel27.setText("Page Editor");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/on-button.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);

        jMenu1.setText("File");

        jMenuItem4.setText("New Paper");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Open");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Import");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Close");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Insert");

        jMenuItem7.setText("MCQ Question");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Structured Question");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Essay Question");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Image");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Table");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("View");

        jMenuItem13.setText("View PDF");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tools");

        jMenuItem14.setText("Bloom's Taxonomy Help");
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Search Past Questions");
        jMenu5.add(jMenuItem15);

        jMenuItem16.setText("View Syllabus");
        jMenu5.add(jMenuItem16);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Share");

        jMenuItem17.setText("Send to Moderator");
        jMenu6.add(jMenuItem17);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Inbox");

        jMenuItem18.setText("Go to Inbox");
        jMenu7.add(jMenuItem18);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(newPaper1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(newPaper, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel2)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(newPaper2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel3)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(newPaper5, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel24)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(newPaper4, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel25)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(newPaper6, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel26)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(newPaper3, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        					.addGap(407)
        					.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabel27))
        			.addContainerGap(425, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jButton6, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(newPaper2, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper1, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper5, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper4, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper6, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(newPaper3, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))))
        			.addGap(2)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(0, 0, Short.MAX_VALUE)
        					.addComponent(jLabel1))
        				.addComponent(jLabel27)
        				.addComponent(jLabel3)
        				.addComponent(jLabel25)
        				.addComponent(jLabel26)
        				.addComponent(jLabel24)
        				.addComponent(jLabel2))
        			.addGap(708))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaperActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void newPaper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper1ActionPerformed

    private void newPaper2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper2ActionPerformed

    private void newPaper3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper3ActionPerformed

    private void newPaper4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper4ActionPerformed

    private void newPaper5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper5ActionPerformed

    private void newPaper6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JButton newPaper;
    private javax.swing.JButton newPaper1;
    private javax.swing.JButton newPaper2;
    private javax.swing.JButton newPaper3;
    private javax.swing.JButton newPaper4;
    private javax.swing.JButton newPaper5;
    private javax.swing.JButton newPaper6;
    // End of variables declaration//GEN-END:variables
}
