/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp;

import java.awt.SystemColor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;

import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import de.nixosoft.jlr.JLRGenerator;
import de.nixosoft.jlr.JLROpener;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.HierarchyListener;
import java.awt.event.HierarchyEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseMotionAdapter;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;



import java.util.*;
import javax.swing.UIManager;
import com.alee.laf.WebLookAndFeel;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author ViduraDan
 * @param <strsetter>
 */
public class main1_frame extends javax.swing.JFrame {

    /**
     * Creates new form main_frame
     */
	
    public String paper;
	
	public static HashMap < Integer,Object> mapper=new HashMap();
	public static HashMap<Integer,Object> smapper=new HashMap();
	public static HashMap<Integer ,Object> stmapper=new HashMap();
	public static HashMap<Integer,Object>strmapper=new HashMap();
	public static HashMap<Integer,Object>esmapper=new HashMap();
	
	
	
	public int tcq=0;
	public Double tmc=0.0;
	
	public int mcc=0;
	public Double mcm=0.0;
	public int sc=0;
	public Double tms=0.0;
	
	public int ec=0;
	public Double mec=0.0;
	
	mcqseter a;
	
	private String end="\\end{expaper}\r\n" +
			"\\end{document}\r\n ";
	private  String  endmark="\\begin{center}\r\n"+
             "----- ***** -----\r\n"+
              "\\end{center}\r\n";
	
	private String stmcq="\\begin{subqlist}\r\n";
	private String enmcq="\\end{subqlist}\r\n"+
                           "}\r\n";
	public static String mcq="";
	public static String str="";
	public static String es="";
	
	
    public main1_frame() {
        initComponents();

    }
    public void fillComboBox()
	{
		try{
			Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/pro_db?useSSL=true","root","mysql");
			Statement st=connection.createStatement();
			String query="SELECT DISTINCT(Area) FROM bloom";
			ResultSet rs=st.executeQuery(query);
			
			while(rs.next()){
				domain.addItem(rs.getString("Area"));
			}
			}
		catch(Exception e){
			e.printStackTrace();
		}
	}
    public void reset(){
    	tcq=0;
    	tmc=0.0;
    	tmc=0.0;
    	mcm=0.0;
    	sc=0;
    	tms=0.0;
    	ec=0;
    	mec=0.0;
    	
    	
    }
     
    public  void mcqset() {
		
		String x="";
	   	 for (Object o : this.mapper.values()){
	   		   mcqbundel a=(mcqbundel)o;
	   		   x+=a.get();
	   		 } 
	   	 this.mcq=x;
	   	 }
     
     
     
     public void strset(){
    	String x="";
    	for (Object o: this.stmapper.values()){
    		strclass a=(strclass)o;
    		x+=a.get();
    	}
    	this.str=x;
     }
    /*public void esset(){
    	String x="";
    	for (Object o:this.esmapper.values()){
    		essayclass a=(essayclass)o;
    		x+=a.get();
    	}
    	this.es=x;
    } */
     
     
    public void fillquestion(){
    	try{
			Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/pro_db?useSSL=true","root","mysql");
			Statement st=connection.createStatement();
			String query="SELECT * FROM ques";
			ResultSet rs=st.executeQuery(query);
			
			while(rs.next()){
				subject.addItem(rs.getString("Subject"));
				module.addItem(rs.getString("Module"));
				dom1.addItem(rs.getString("Bloom"));
			}
			}
		catch(Exception e){
			e.printStackTrace();
		}
    	
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        newPaper = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newPaper1 = new javax.swing.JButton();
        newPaper2 = new javax.swing.JButton();
        newPaper3 = new javax.swing.JButton();
        newPaper4 = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        newPaper6 = new javax.swing.JButton();
        mcq_1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tq = new javax.swing.JTextField();
        tq.setText("0");
        tm = new javax.swing.JTextField();
        tm.setText("0");
        mc = new javax.swing.JTextField();
        mc.setText("0");
        mm = new javax.swing.JTextField();
        mm.setText("0");
        en = new javax.swing.JTextField();
        en.setText("0");
        em = new javax.swing.JTextField();
        em.setText("0");
        sn = new javax.swing.JTextField();
        sn.setText("0");
        sm = new javax.swing.JTextField();
        sm.setText("0");
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        
       
        jButton2 = new javax.swing.JButton();
        structure = new javax.swing.JButton();
        structure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                str_ActionPerformed(evt);
            }
        });
        
        
        /*structure.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		strseter a=new strseter(this);
        		a.setVisible(true);
        	}
        });*/
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        module = new javax.swing.JComboBox<>();
        dom1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        domain = new javax.swing.JComboBox<>();
        
        
        
        
        
        domain.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		BT a=new BT();
				a.setVisible(true);
        	}
        });
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        power = new javax.swing.JButton();
       
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem6.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem12.setText("jMenuItem12");

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QseTeX");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        newPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/Folder_32x32.png"))); // NOI18N
        newPaper.setActionCommand("New Paper");
        newPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaperActionPerformed(evt);
            }
        });

        jLabel1.setText("New Paper");

        newPaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/newpaper.png"))); // NOI18N
        newPaper1.setActionCommand("New Paper");
        newPaper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper1ActionPerformed(evt);
            }
        });

        newPaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/diskette.png"))); // NOI18N
        newPaper2.setActionCommand("New Paper");
        newPaper2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper2ActionPerformed(evt);
            }
        });

        newPaper3.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/square.png"))); // NOI18N
        newPaper3.setActionCommand("New Paper");
        newPaper3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper3ActionPerformed(evt);
            }
        });

        newPaper4.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/email.png"))); // NOI18N
        newPaper4.setActionCommand("New Paper");
        newPaper4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper4ActionPerformed(evt);
            }
        });

        pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/pdf.png"))); // NOI18N
        pdf.setActionCommand("New Paper");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper5ActionPerformed(evt);
            }
        });

        newPaper6.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/inbox (1).png"))); // NOI18N
        newPaper6.setActionCommand("New Paper");
        newPaper6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaper6ActionPerformed(evt);
            }
        });
        
        mcq_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/list.png"))); // NOI18N
        mcq_1.setActionCommand("MCQ");
        mcq_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcq_1ActionPerformed(evt);
            }
        });
        
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });

        jLabel2.setText("Open");

        jLabel3.setText("Save");

        jLabel4.setText("Total Questions");

        jLabel5.setText("Total Marks");

        jLabel6.setText("MCQ");

        jLabel7.setText("Esaay");

        jLabel8.setText("Structutred");

        jLabel9.setText("MCQ");

        jLabel10.setText("Esaay");

        jLabel11.setText("Structutred");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel12.setText("Add Questions");

       
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/writing.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        structure.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/test.png"))); // NOI18N

        jLabel13.setText("MCQ");

        jLabel15.setText("Essay");

        jLabel16.setText("Structured");

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel17.setText("Search Questions");

        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Subject");

        jLabel18.setText("Module");

        jLabel19.setText("Bloom's Tax. Domain");

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel20.setText("Syllabus View");

        jLabel21.setText("Domain");

        domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        
       /* domain.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				BT a=new BT();
				a.setVisible(true);
			}
			
		});*/

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel22.setText("Bloom's Taxanomy Help");

        jLabel23.setText("Subject");

        jButton4.setText("Search");

        jScrollPane2.setViewportView(jList1);

        jLabel24.setText("PDF View");

        jLabel25.setText("Send");

        jLabel26.setText("Inbox");

        jLabel27.setText("   Style file");

        power.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/on-button.png"))); // NOI18N
        power.setBorder(null);
        power.setBorderPainted(false);

        jMenu1.setText("File");

        jMenuItem4.setText("New Paper");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Open");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Import");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Close");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Insert");

        jMenuItem7.setText("MCQ Question");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Structured Question");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Essay Question");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Image");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Table");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("View");

        jMenuItem13.setText("View PDF");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tools");

        jMenuItem14.setText("Bloom's Taxonomy Help");
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Search Past Questions");
        jMenu5.add(jMenuItem15);

        jMenuItem16.setText("View Syllabus");
        jMenu5.add(jMenuItem16);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Share");

        jMenuItem17.setText("Send to Moderator");
        jMenu6.add(jMenuItem17);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Inbox");

        jMenuItem18.setText("Go to Inbox");
        jMenu7.add(jMenuItem18);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPaper1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPaper2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel24)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPaper4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel25)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPaper6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel26)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(newPaper3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tq, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mcq_1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(69, 69, 69)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(structure, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel16)))
                                .addGap(45, 45, 45))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12))
                                .addContainerGap(245, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5)
                                    .addComponent(jSeparator6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dom1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(power, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(power, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPaper2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPaper1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPaper4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPaper6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPaper3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel27)
                    .addComponent(jLabel3)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(structure, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(mcq_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(13, 13, 13)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(4, 4, 4))
        );
        fillComboBox();
        fillquestion();
        tex = new JTextArea();
        jScrollPane1.setViewportView(tex);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void mcq_1ActionPerformed(java.awt.event.ActionEvent evt){
    	
    	//mcqseter a=new mcqseter(this);
    	if(a==null){
    		a=new mcqseter(this);
    	}
        a.setVisible(true);
    }
    
  private void str_ActionPerformed(java.awt.event.ActionEvent evt){
    	
    	strsetter2 a=new strsetter2(this);
    	a.setVisible(true);
    }
  
    
 
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt){
    	
    	search_question a=new search_question();
        a.setVisible(true);
    }
    
    private void newPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaperActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    	this.mcq="";
    	this.reset();
    	tex.setText("");
    	mcc=0;
    	mcm=0.0;
    	sc=0;
    	tms=0.0;
    	
    	//mapper=new HashMap();
    	mapper.clear();
    	//newp1 a=new newp1(this);
        //a.setVisible(true);
    	
    	
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void newPaper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper1ActionPerformed
        // TODO add your handling code here:
    	this.mcq="";
    	this.reset();
    	tex.setText("");
    	mcc=0;
    	mcm=0.0;
    	tq.setText("0");
	    tm.setText("0");
	    mc.setText("0");
	    mm.setText("0");
    	//mapper=new HashMap();
    	mapper.clear();
    	newp1 amcq=new newp1(this);
        amcq.setVisible(true);
    	
    	
    	
    }//GEN-LAST:event_newPaper1ActionPerformed
    
public void strupd(){
	String upd=paper+mcq+str+es+endmark+end;
	try{
		  PrintWriter writer = new PrintWriter(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex", "UTF-8");
		  writer.println(upd);
		  writer.close();
		  
		 /* gp a=new gp();
		  a.frmPrototype.setVisible(true);*/
		 // g.setVisible(true);
		  DefaultListModel listModel = new DefaultListModel();
		  tex.setText("");
		  try{
		  BufferedReader in=new BufferedReader(new FileReader(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex"));
		  String line=null;
		  while((line=in.readLine())!=null){
			  listModel.addElement(line);
			  tex.append(line+"\n");
		  }
		  //a.tex.setModel(listModel);
		  //tex.setModel(listModel);
		  }
		  catch(Exception e){
			  e.printStackTrace();
			  
		  }
		  
		  
		  
		  
	  }catch(Exception e){
		  e.printStackTrace();
		 
		  
	  } 
	
	
	
	
}	
	
public void esupd(){
	String upd=paper+mcq+str+es+endmark+end;
	try{
		  PrintWriter writer = new PrintWriter(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex", "UTF-8");
		  writer.println(upd);
		  writer.close();
		  
		 /* gp a=new gp();
		  a.frmPrototype.setVisible(true);*/
		 // g.setVisible(true);
		  DefaultListModel listModel = new DefaultListModel();
		  
		  
		  
		  tex.setText("");
		  try{
		  BufferedReader in=new BufferedReader(new FileReader(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex"));
		  String line=null;
		  while((line=in.readLine())!=null){
			  listModel.addElement(line);
			  tex.append(line+"\n");
		  }
		  //a.tex.setModel(listModel);
		  //tex.setModel(listModel);
		  }
		  catch(Exception e){
			  e.printStackTrace();
			  
		  }
		  
		  
		  
		  
	  }catch(Exception e){
		  e.printStackTrace();
		 
		  
	  } 
}	
	
  
    
public void mcqupd(){
    	
    	String upd=paper+mcq+str+es+endmark+end;
    	try{
			  PrintWriter writer = new PrintWriter(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex", "UTF-8");
			  writer.println(upd);
			  writer.close();
			  
			 /* gp a=new gp();
			  a.frmPrototype.setVisible(true);*/
			 // g.setVisible(true);
			  DefaultListModel listModel = new DefaultListModel();
			  tex.setText("");
			  try{
			  BufferedReader in=new BufferedReader(new FileReader(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)\\latex.tex"));
			  String line=null;
			  while((line=in.readLine())!=null){
				  listModel.addElement(line);
				  tex.append(line+"\n");
			  }
			  //a.tex.setModel(listModel);
			  //tex.setModel(listModel);
			  }
			  catch(Exception e){
				  e.printStackTrace();
				  
			  }
			  
			  
			  
			  
		  }catch(Exception e){
			  e.printStackTrace();
			 
			  
		  } 
    	
    	
    	
    	
    }
   
    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper2ActionPerformed
    // TODO add your handling code here:
       this.setVisible(false);
       login a=new login();
       a.setVisible(true);
      }//GEN-LAST:event_newPaper2ActionPerformed
    
    private void newPaper2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper2ActionPerformed
        // TODO add your handling code here:
    	JFileChooser fs=new JFileChooser("C:\\");
	    fs.setDialogTitle("Save a File");
	    fs.setFileFilter(new FileTypeFilter(".txt","Text File"));
	    fs.setFileFilter(new FileTypeFilter(".tex","latex File"));
	    int result=fs.showSaveDialog(null);
	    if(result == JFileChooser.APPROVE_OPTION){
	    	String content = tex.getText();
	    	File fi =fs.getSelectedFile();
	    	try{
	    		FileWriter fw=new FileWriter(fi.getPath());
	    		
	    		
	    		fw.write(content);
	    		fw.flush();
	    		fw.close();
	    		
	    	}catch(Exception e2){
	    		
	    		JOptionPane.showMessageDialog(null,e2.getMessage());
	    	}
	    	
	    	
	    	
	    }
	    
	    
	    
    }//GEN-LAST:event_newPaper2ActionPerformed

    private void newPaper3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper3ActionPerformed

    private void newPaper4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper4ActionPerformed

    private void newPaper5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper5ActionPerformed
        // TODO add your handling code here:
    	try{//create pdf
			File desktop = new File(System.getProperty("user.home")	+ "\\" + "Desktop");
			File wd = new File(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)");
			File invoice1 = new File(System.getProperty("user.home")+"\\Desktop\\MyFiles\\java\\fwdtemplates(1)"+"\\"+ "latex.tex");
			JLRGenerator pdfGen = new JLRGenerator();

			pdfGen.generate(invoice1, desktop, wd);
			File pdf1 = pdfGen.getPDF();

		

			JLROpener.open(pdf1);}catch(IOException ex){ex.printStackTrace();}
    	
    	
    }//GEN-LAST:event_newPaper5ActionPerformed

    private void newPaper6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaper6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPaper6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    	//BT a=new BT();
		//a.setVisible(true);
    }//GEN-LAST:event_jComboBox4ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	/*Essay1 e=new Essay1(this);
    	e.setVisible(true);/*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main1_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main1_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main1_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main1_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main1_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mcq_1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton structure;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton power;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JComboBox<String> module;
    private javax.swing.JComboBox<String> dom1;
    private javax.swing.JComboBox<String> domain;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField tq;
    public javax.swing.JTextField tm;
    public javax.swing.JTextField mc;
    public javax.swing.JTextField mm;
    public javax.swing.JTextField en;
    public javax.swing.JTextField em;
    public  javax.swing.JTextField sn;
    public javax.swing.JTextField sm;
    private javax.swing.JButton newPaper;
    private javax.swing.JButton newPaper1;
    private javax.swing.JButton newPaper2;
    private javax.swing.JButton newPaper3;
    private javax.swing.JButton newPaper4;
    private javax.swing.JButton pdf;
    private javax.swing.JButton newPaper6;
    public JTextArea tex;
    // End of variables declaration//GEN-END:variables
}
