package gp;
import java.util.HashMap ;

import javax.swing.GroupLayout.Alignment ;
import javax.swing.GroupLayout ;
import javax.swing.LayoutStyle.ComponentPlacement ;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ViduraDan
 */
public class stadder extends javax.swing.JFrame {
	public  String  tst1="";
	public  String  tp1 ="Above";
	
    

   
	
	main1_frame g;
    public stadder(main1_frame a) {
    	space.setColumns(10);
    	Space.setText("Space");
        initComponents();
        g=a;
    }
    
    
  
      
	
	





	public stadder(ActionListener actionListener) {
		// TODO Auto-generated constructor stub
		
	}











	@SuppressWarnings("unused")
    private void addtActionPerformed(java.awt.event.ActionEvent evt){
   	 // TODO add your handling code here:
   
       
   	
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	setTitle("MCQ"); 
        question_1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JButton();
        
        add.addActionListener(new ActionListener() {
public void actionPerformed(ActionEvent e) {
 
 
 int no= (int) qno.getValue();
 int mark=(int)marks.getValue();
g.mcc+=1;
g.mcm+=mark;
g.mc.setText(String.valueOf(g.mcc));
g.mm.setText(String.valueOf(g.mcm));
g.tq.setText(String.valueOf(g.mcc));
g.tm.setText(String.valueOf(g.mcm));
String dtable="";
String utable="";

if(tst1!=""){
   if(tp1=="Above"){
	   utable =tst1;
	   
   }
   else{
	   dtable=tst1; 
   }
}



String STD = utable+"\\subquestion{"+question.getText()+"\r\n"+dtable+
"\\begin{enumerate}\r\n"+
"\\qmarks{"+marks.getValue()+"}\r\n"+
"\\answer{"+space.getText()+"in}\r\n"+
"\\end{enumerate}\r\n"+
"}\r\n";


/*
if(main1_frame.stmapper.containsKey(no)){
	stadder testa=(stadder)main1_frame.stmapper.get(no);
	main1_frame.stmapper.remove(no);
	testa.title1="\\question {"+title1.getText()+".\r\n";
	testa.utitle1=title1.getText();
	testa.std+=STD;
	//System.out.println(testa.std);
	main_frame.mapper.put(no,testa);
	
}
else{
	stadder testa=new stadder(no);
	testa.title1="\\question {"+title1.getText()+".\r\n";
	testa.utitle1=title1.getText();
	testa.std+=STD;
    main_frame.mapper.put(no,testa);
}
        		
   question.setText("");
  
   
   this.stdset();
   g.stdupd();*/
   
  
 }
 
 
 
 /*public void getwhole(){
	 
	 for (Object o : main_frame.mapper.values()){
		 stadder a=(stadder)o;
		   System.out.println(a.title1);
		   System.out.println(a.std);
		   System.out.println("_______________");
		   System.out.print("\n\n\n");
		}
	 }*/
        	
 /*public void stdset(){
	 String x="";
	 for (Object o : main_frame.mapper.values()){
		 stadder a=(stadder)o;
		   x+=a.get();
		  
		} 
	 main_frame.std=x;
} */      	 
            
			private void setVisible(boolean b) {
				// TODO Auto-generated method stub
				dispose();
				
			}
        });
       
       // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      
        question_1.setText("      Question");
        qno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		
        		
        		Integer no= (Integer) qno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    
        	    
        	    
        		if(main1_frame.stmapper.containsKey(r)){
        			strclass o=(strclass)main1_frame.stmapper.get(r);
        	    	//String tit=o.fsq;
        	    	
        	    	//title1.setText(tit);
        			
        	    }
        		else{
        			 title1.setText("");
        		}
        	    
        	    
        		
        	}
        });
       
         
        qno.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        add.setText("ADD");
        
        
       
        
        addt.addActionListener(new java.awt.event.ActionListener() {
    		public void actionPerformed(java.awt.event.ActionEvent evt) {
    			addtActionPerformed(evt);
    		}
    	});
        
        
        marks.setModel(new SpinnerNumberModel(2, 0, 10, 1));
        title1.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblTitle, GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(question_1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        									.addGap(23)))
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(title1)
        								.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        							.addGap(26)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblTitleNo)
        									.addGap(18)
        									.addComponent(qno, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
        								.addComponent(addt, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        								.addComponent(btnChangeTitle)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblMarks, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(marks, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))))
        						.addComponent(add, Alignment.TRAILING)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(Space, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(space, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblInches)
        					.addPreferredGap(ComponentPlacement.RELATED, 590, Short.MAX_VALUE)
        					.addComponent(blm)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(14)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblTitle)
        				.addComponent(title1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(qno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTitleNo))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(32)
        							.addComponent(blm))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(space, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(Space, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(26)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(question_1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnChangeTitle))
        					.addGap(18)
        					.addComponent(addt)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(marks, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblMarks))
        					.addGap(13)
        					.addComponent(lblInches)))
        			.addGap(246)
        			.addComponent(add)
        			.addContainerGap())
        );
        blm.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	   BT x=new BT();
        	   x.setVisible(true);
        	}
        });
        /*btnChangeTitle.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	   int no=(int) qno.getValue();
        	   if(main_frame.mapper.containsKey(no)){
        		   stadder o=(stadder)main_frame.mapper.get(no);
       	    	o.title1="\\question {"+title1.getText()+".\r\n";
       	    	o.utitle1=title1.getText();
       	   }else{
       		   title1.setText("");
       	   }
        	   
        	   
        	}
        });*/
        
        jScrollPane1.setViewportView(question);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JLabel question_1;
    private javax.swing.JScrollPane jScrollPane1;
    private final JButton addt = new JButton("ADD Table");
    public  static JTextField title1 = new JTextField();
    private final JLabel lblTitle = new JLabel("      Title");
    private final JSpinner qno = new JSpinner();
    private final JLabel lblTitleNo = new JLabel("Title No:");
    private final JTextArea question = new JTextArea();
    private final JButton btnChangeTitle = new JButton("Change Title");
    private final JSpinner marks = new JSpinner();
    private final JLabel lblMarks = new JLabel("Marks");
    private final JButton blm = new JButton("Bloom's tex");
    private final JLabel Space = new JLabel();
    private final JTextField space = new JTextField();
    private final JLabel lblInches = new JLabel("Inches");
}

