/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
/**
 *
 * @author User
 */
public class strseter extends javax.swing.JFrame {

    /**
     * Creates new form strseter
     */
	
	public  String  tst="";
	public  String  tp ="Above";
	main1_frame g;
	
    public strseter(main1_frame a) {
        initComponents();
        g=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qno = new javax.swing.JSpinner();
        
        qno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		Integer no= (Integer) qno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    
        	    if(g.stmapper.containsKey(r)){
        	    	strclass o=(strclass)g.stmapper.get(r);
        	    	String tit=o.utitle;
        	    	stro st1=(stro)o.strlist.get(1);
        	    	Title.setText(tit);
        	        question.setText(st1.question);
        	        Double marks=Double.parseDouble(st1.mark);
        	        Marks.setValue(marks);
        	       
        	       
        	  }else{
        		Title.setText("");
      			question.setText("");
       	         }
        	}
        });
        
        qno.setModel(new SpinnerNumberModel(1, 1, 20, 1));
        jLabel3 = new javax.swing.JLabel();
        sqno = new javax.swing.JSpinner();
        sqno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		Integer no= (Integer) sqno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    Integer no1=(Integer)qno.getValue();
        		strclass mcb=(strclass)g.stmapper.get(no1);
        		if(mcb.strlist.containsKey(no)){
            		stro o=(stro)mcb.strlist.get(no);
            		question.setText(o.uquestion);
        	    	Double marks=Double.parseDouble(o.mark);
        	    	Marks.setValue(marks);
        	    	Area.setSelectedItem(o.btarea);
            			
            			
            		}
            		else{
            			question.setText("");
             	      }
        	}
        });
        sqno.setModel(new SpinnerNumberModel(1, 1, 8, 1));
        changetitle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Marks = new javax.swing.JSpinner();
        Marks.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 1.0));
        Table = new javax.swing.JButton();
        Bloom = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Area = new javax.swing.JComboBox<>();
        space = new javax.swing.JSpinner();
        space.setModel(new SpinnerNumberModel(0.0, 0.0, 10.0, 1.0));
        jLabel7 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        setTitle("Structure Setter");

        jLabel1.setText("  Title");

        jLabel2.setText(" Question No");

        jLabel3.setText(" Sub Part No");

        changetitle.setText("Change Title");
        changetitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText(" Question");

        jLabel5.setText("      Marks");

        Table.setText("Add Table");
        Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	TableActionPerformed(evt);
            }
        });

        Bloom.setText("Bloom Texanomy");
        Bloom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloomActionPerformed(evt);
            }
        });

        jLabel6.setText("  Area");

        Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remembering", "Understanding", "Applying", "Analyzing", "Evaluating", "Creating" }));

        jLabel7.setText("Space");

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        question = new javax.swing.JTextArea();
        
                question.setColumns(20);
                question.setRows(5);
        
        Pic = new JButton("Picture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(space, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(Pic))
        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(Title))
        								.addComponent(question, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 881, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(71)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(Table))
        								.addGroup(layout.createSequentialGroup()
        									.addGap(29)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(layout.createSequentialGroup()
        											.addGap(71)
        											.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.RELATED)
        											.addComponent(Marks, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(jLabel2)
        											.addGap(21)
        											.addComponent(qno, GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(jLabel3)
        											.addGap(27)
        											.addGroup(layout.createParallelGroup(Alignment.LEADING)
        												.addComponent(Bloom, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        												.addComponent(sqno, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(changetitle))))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addContainerGap(1081, Short.MAX_VALUE)
        					.addComponent(Add, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(1078)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Area, 0, 114, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Title, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(qno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(changetitle))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(24)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel3)
        						.addComponent(sqno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(31)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel5)
        						.addComponent(Marks, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(33)
        					.addComponent(Table))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(question, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(19)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel7)
        						.addComponent(space, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Bloom)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(Pic)))
        			.addGap(18)
        			.addComponent(jLabel6)
        			.addGap(11)
        			.addComponent(Area, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(59)
        			.addComponent(Add)
        			.addGap(123))
        );
        getContentPane().setLayout(layout);

        qno.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	int no=(int) qno.getValue();
   	   if(g.stmapper.containsKey(no)){
  	    	strclass o=(strclass)g.stmapper.get(no);
  	    	o.title="\\question {"+Title.getText()+".\r\n";
  	    	o.utitle=Title.getText();
  	   }else{
  		   Title.setText("");
  	   }
   	   
    	
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	
    	
    }  
    
    private void TableActionPerformed(java.awt.event.ActionEvent evt){
      	  table4 a=new table4(this);
          a.setVisible(true);
      	
      }

    private void BloomActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	new BT().setVisible(true);
    }                                        

    private void AddActionPerformed(java.awt.event.ActionEvent evt) { 
        
    	 int no= (int) qno.getValue();
    	 
  		 Double mark=(Double)Marks.getValue();
  		 int sqn=(int)sqno.getValue();
    	
    	
    	String dtable="";
   		String utable="";
           
   		if(tst!=""){
   		   if(tp=="Above"){
   			   utable =tst;
   			   
   		   }
   		   else{
   			   dtable=tst; 
   		   }
   		}
    	
   		String stitle="\\newpage\r\n"+"\\question{"+Title.getText()+"\r\n";
    	String str=
    		  utable+"\\subquestion{"+ question.getText() +"\r\n" + dtable+ 

              "\\qmarks{"+Marks.getValue()+"}\r\n"+

              "\\answer{"+space.getValue()+"in}\r\n"+

              "}\r\n";
              
             
    	String start="\\begin{subqlist}\r\n";
    	String end="\\end{subqlist}\r\n";
    	
    	
    	
    	if(g.stmapper.containsKey(no)){
    		strclass testa=(strclass)g.stmapper.get(no);
    		g.stmapper.remove(no);
    	    testa.title="\\newpage\r\n"+"\\question {"+Title.getText()+".\r\n";
   			testa.utitle=Title.getText();
    		if(testa.strlist.containsKey(sqn)){
    			System.out.print(testa.mark);
    			stro r=(stro)testa.strlist.get(sqn);
    			testa.strlist.remove(sqn);
    			String oldmark=r.mark;
    			r.qno= sqn;
    	        r.question=str;
    	        r.uquestion=question.getText();
        		r.mark=Marks.getValue().toString();
        		r.btarea=Area.getSelectedItem().toString();
        		if(!testa.CheckMark()){
        			JOptionPane.showMessageDialog(null, "Marks for total questions exeeded the Limit");
        			
        		}else{
        		testa.strlist.put(sqn,r);
        		}
       	       }
    		else{
    			stro t=new stro(no,str);
    			t.uquestion=question.getText();
        		t.qno= sqn;
        		t.mark=Marks.getValue().toString();
        		t.btarea=Area.getSelectedItem().toString();
        		testa.strlist.put(sqn,t);
    			}
    		g.stmapper.put(no,testa);
    		
    		
    	}else{
    	
    		strclass r=new strclass(no);
    		r.title=stitle;
    		r.utitle=Title.getText();
    		stro t=new stro(no,str);
    		t.uquestion=question.getText();
    		t.qno= sqn;
    		t.mark=Marks.getValue().toString();
    		t.btarea=Area.getSelectedItem().toString();
    		r.strlist.put(sqn,t);
    		g.stmapper.put(no,r);
    	}
    	
    	g.strset();
		g.strupd();
		tst="";
    	
    	
    	
       
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(strseter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(strseter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(strseter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(strseter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new strseter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton changetitle;
    private javax.swing.JButton Table;
    private javax.swing.JButton Bloom;
    private javax.swing.JButton Add;
    private javax.swing.JComboBox<String> Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner qno;
    private javax.swing.JSpinner sqno;
    private javax.swing.JSpinner Marks;
    private javax.swing.JSpinner space;
    private javax.swing.JTextArea question;
    private javax.swing.JTextField Title;
    private JButton Pic;
}
