/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp;
import java.util.HashMap ;

import javax.swing.GroupLayout.Alignment ;
import javax.swing.GroupLayout ;
import javax.swing.LayoutStyle.ComponentPlacement ;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author User
 */
public class test extends javax.swing.JFrame {
	public  String  tst="";
	public  String  tp ="Above";
	
    

    /**
     * Creates new form mcq
     */
	
	main_frame g;
    public test(main_frame a) {
        initComponents();
        g=a;
    }
    
    
    @SuppressWarnings("unused")
    private void addtActionPerformed(java.awt.event.ActionEvent evt){
   	 // TODO add your handling code here:
   
       table2 a=new table2(this);
       a.setVisible(true);
   	
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	setTitle("MCQ"); 
        question_1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        op4.setColumns(10);
    	op3.setColumns(10);
    	op2.setColumns(10);
    	op1.setColumns(10);
        
        add.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
 
 
 int no= (int) qno.getValue();
 int mark=(int)marks.getValue();
 g.mcc+=1;
 g.mcm+=mark;
 g.mc.setText(String.valueOf(g.mcc));
 g.mm.setText(String.valueOf(g.mcm));
 g.tq.setText(String.valueOf(g.mcc));
 g.tm.setText(String.valueOf(g.mcm));
String dtable="";
String utable="";

if(tst!=""){
   if(tp=="Above"){
	   utable =tst;
	   
   }
   else{
	   dtable=tst; 
   }
}



String MCQ = utable+"\\subquestion{"+question.getText()+"\r\n"+dtable+
"\\begin{enumerate}\r\n"+
"\\item "+op1.getText()+"\r\n"+ 
"\\item "+op2.getText()+"\r\n"+
"\\item "+op3.getText()+"\r\n"+
"\\item "+op4.getText()+"\r\n"+
"\\end{enumerate}\r\n"+
"\\qmarks{"+marks.getValue()+"}\r\n"+
"}\r\n";



if(main_frame.mapper.containsKey(no)){
	mcqq testa=(mcqq)main_frame.mapper.get(no);
	main_frame.mapper.remove(no);
	testa.title="\\question {"+title.getText()+".\r\n";
	testa.utitle=title.getText();
	testa.mcq+=MCQ;
	//System.out.println(testa.mcq);
	main_frame.mapper.put(no,testa);
	
}
else{
	mcqq testa=new mcqq(no);
	testa.title="\\question {"+title.getText()+".\r\n";
	testa.utitle=title.getText();
	testa.mcq+=MCQ;
    main_frame.mapper.put(no,testa);
}
        		
   question.setText("");
   op1.setText("");
   op2.setText("");
   op3.setText("");
   op4.setText(""); 
   
   this.mcqset();
   g.mcqupd();
   tst="";
  
 }
 
 
 
 public void getwhole(){
	 
	 for (Object o : main_frame.mapper.values()){
		   mcqq a=(mcqq)o;
		   System.out.println(a.title);
		   System.out.println(a.mcq);
		   System.out.println("_______________");
		   System.out.print("\n\n\n");
		}
	 }
        	
 public void mcqset(){
	 String x="";
	 for (Object o : main_frame.mapper.values()){
		   mcqq a=(mcqq)o;
		   x+=a.get();
		  
		} 
	 main_frame.mcq=x;
}       	 
            
			private void setVisible(boolean b) {
				// TODO Auto-generated method stub
				dispose();
				
			}
        });
       
       // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      
        question_1.setText("      Question");
        qno.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        		
        		
        		Integer no= (Integer) qno.getValue();
        	    String a=no.toString();
        	    int r=no.intValue();
        	    
        	    
        	    
        		if(g.mapper.containsKey(r)){
        	    	mcqq o=(mcqq)g.mapper.get(r);
        	    	String tit=o.utitle;
        	    	
        	    	title.setText(tit);
        			
        	    }
        		else{
        			 title.setText("");
        		}
        	    
        	    
        		
        	}
        });
       
         
        qno.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        
        

        

        jLabel2.setText("      Option 1");

        jLabel3.setText("      Option 2");

        jLabel4.setText("      Option 3");

        jLabel5.setText("      Option 4");

        add.setText("ADD");
        
        
       
        
        addt.addActionListener(new java.awt.event.ActionListener() {
    		public void actionPerformed(java.awt.event.ActionEvent evt) {
    			addtActionPerformed(evt);
    		}
    	});
        
        
        marks.setModel(new SpinnerNumberModel(2, 0, 10, 1));
        title.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblTitle, GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(question_1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        							.addGap(23)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(title)
        						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        					.addGap(26)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblTitleNo)
        							.addGap(18)
        							.addComponent(qno, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
        						.addComponent(addt, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnChangeTitle)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblMarks, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(marks, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        						.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(op2, Alignment.LEADING, 675, 675, 675)
        						.addComponent(op3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        						.addComponent(op4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        						.addComponent(op1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
        					.addGap(58)
        					.addComponent(blm))
        				.addComponent(add, Alignment.TRAILING))
        			.addContainerGap())
        );
        blm.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	   BT x=new BT();
        	   x.setVisible(true);
        	}
        });
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(14)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblTitle)
        				.addComponent(title, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(qno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTitleNo))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        					.addGap(32)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        						.addComponent(op1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(blm))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        						.addComponent(op2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        						.addComponent(op3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        						.addComponent(op4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(26)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(question_1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnChangeTitle))
        					.addGap(18)
        					.addComponent(addt)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(marks, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblMarks))))
        			.addGap(38)
        			.addComponent(add)
        			.addContainerGap())
        );
        
        btnChangeTitle.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	   int no=(int) qno.getValue();
        	   if(g.mapper.containsKey(no)){
       	    	mcqq o=(mcqq)g.mapper.get(no);
       	    	o.title="\\question {"+title.getText()+".\r\n";
       	    	o.utitle=title.getText();
       	   }else{
       		   title.setText("");
       	   }
        	   
        	   
        	}
        });
        
        jScrollPane1.setViewportView(question);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mcq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JLabel question_1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private final JButton addt = new JButton("ADD Table");
    public  static JTextField title = new JTextField();
    private final JLabel lblTitle = new JLabel("      Title");
    private final JSpinner qno = new JSpinner();
    private final JLabel lblTitleNo = new JLabel("Title No:");
    private final JTextField op1 = new JTextField();
    private final JTextField op2 = new JTextField();
    private final JTextField op3 = new JTextField();
    private final JTextField op4 = new JTextField();
    private final JTextArea question = new JTextArea();
    private final JButton btnChangeTitle = new JButton("Change Title");
    private final JSpinner marks = new JSpinner();
    private final JLabel lblMarks = new JLabel("Marks");
    private final JButton blm = new JButton("Bloom's tex");
}
